sonar.verbose=true
sonar.organization=SumeetKumarSing
sonar.projectKey=sumeetkumarsing-key1
sonar.projectName=saidemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
